@description ReAerah
@author dopp
@version 18
@provides ReAerah.ReaperThemeZip https://github.com/doppgit/theme/raw/61f56011d04e54454be06cd6db21f07575f2ba02/ReAerah.ReaperThemeZip
@link
  Forum Thread https://forum.cockos.com/showthread.php?t=191616
  font Digital-7-Mono http://www.styleseven.com/php/get_product.php?product=Digital-7
  font Anita Semi-square http://www.1001freefonts.com/anita_semi_square.font
@screenshot
  TCP default and folder layouts https://imgur.com/a/Dh7FeRg
  MCP fullscreen layouts https://imgur.com/a/VrjGxIt
  settings https://imgur.com/a/O6TNXKX
@about
  ReAerah theme

  Simple, not fancy, compact theme, has a lot of layouts,
  possible to change track/item color settings in REAPER's options for different tastes.
  (for default settings of theme, click Screenshot button and select "settings")

  Install free fonts for proper look (google them or click Website button and select corresponding link):
  Digital-7 Mono
  Anita Semi-square
