@description Default 5.0 Nitpicky Edition
@version 15
@author Lokasenna
@links
  Forum Thread https://forum.cockos.com/showthread.php?t=165040
  Stash Page https://stash.reaper.fm/24878/Default%205.0%20Nitpicky%20Edition.ReaperThemeZip
@screenshot https://i.imgur.com/irCO9qZ.png
@provides Default 5.0 Nitpicky Edition.ReaperThemeZip https://stash.reaper.fm/24878/Default%205.0%20Nitpicky%20Edition.ReaperThemeZip
@about
  Fixes and tiny improvements for the default Reaper 5.0 theme.
