@description RADO-V5-ARTEK
@author Oleg Goryachev
@version 1.0.1
@changelog Changed colours and fonts. Replaced and tuned some PNG Files.
@provides New file 6.ReaperThemeZip https://github.com/Oleg-Artek-Music/Reaper-Daw/raw/master/RADO-V5-ARTEK.ReaperThemeZip
@screenshot
  Main Window https://github.com/Oleg-Artek-Music/Reaper-Daw/raw/master/01.%20Main%20Window.png
  Piano Roll Editor https://github.com/Oleg-Artek-Music/Reaper-Daw/raw/master/02.%20Piano%20Roll%20Editor.png
  Mixer https://github.com/Oleg-Artek-Music/Reaper-Daw/raw/master/03.%20Mixer.png
  Waveform https://github.com/Oleg-Artek-Music/Reaper-Daw/raw/master/04.%20Waveform.png
  Automation https://github.com/Oleg-Artek-Music/Reaper-Daw/raw/master/05.%20Automation.png
  Folder Tracks https://github.com/Oleg-Artek-Music/Reaper-Daw/raw/master/06.%20Folder%20Tracks.png
  Musical Notation https://github.com/Oleg-Artek-Music/Reaper-Daw/raw/master/07.%20Musical%20Notation.png
@about
  Hello everybody! I modified the famous RADO-V4 (by Nick Mortiz) Reaper theme. I tried to make the most convenient environment for my eyes. After 26 years making music it dawned on me that saving eyesight must be the most important thing! I used Comic Sans and Calibri fonts. If you haven't these fonts, you can find them in the Internet. Best regards, Oleg Goryachev.
  https://vk.com/ogsmusic
  https://www.youtube.com/user/ogsmaker/
